# Generated by Django 4.2.3 on 2023-07-22 11:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('cost', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Components',
            },
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Labs',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Location',
            },
        ),
        migrations.CreateModel(
            name='Member_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Member Type',
            },
        ),
        migrations.CreateModel(
            name='Source_Of_Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Source-Of-Expenses',
            },
        ),
        migrations.CreateModel(
            name='Source_of_Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Source-of-Income',
            },
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('amount', models.FloatField(blank=True, null=True)),
                ('date', models.DateField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='studio_app.component')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='studio_app.lab')),
            ],
            options={
                'verbose_name_plural': 'Purchases',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('middleName', models.CharField(blank=True, max_length=255, null=True)),
                ('lastName', models.CharField(max_length=255)),
                ('dateOfBirth', models.DateField()),
                ('registrationNumber', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('idNumber', models.CharField(max_length=255)),
                ('registeredDate', models.DateField(null=True)),
                ('nationality', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=255)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='studio_app.location')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='studio_app.member_type')),
            ],
            options={
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('date', models.DateField(default=datetime.datetime(2023, 7, 22, 14, 15, 6, 860173))),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='studio_app.lab')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='studio_app.source_of_income')),
            ],
            options={
                'verbose_name_plural': 'Income',
            },
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='studio_app.lab')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='studio_app.source_of_expenses')),
            ],
            options={
                'verbose_name_plural': 'Expenses',
            },
        ),
        migrations.AddField(
            model_name='component',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='studio_app.lab'),
        ),
    ]
