# Generated by Django 4.2.3 on 2023-07-24 13:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name_plural': 'Members'},
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 24, 16, 23, 36, 797636)),
        ),
        migrations.CreateModel(
            name='CheckInAndout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('status', models.CharField(max_length=255)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='studio_app.member')),
            ],
            options={
                'verbose_name_plural': 'CheckInAndout',
            },
        ),
    ]
