# Generated by Django 4.2.3 on 2023-11-12 09:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respondedcomponents',
            name='component',
        ),
        migrations.RemoveField(
            model_name='respondedcomponents',
            name='lab',
        ),
        migrations.AddField(
            model_name='respondedcomponents',
            name='labComponent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='studio_app.labcomponent'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 11, 12, 12, 21, 36, 60825)),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 11, 12, 12, 21, 36, 58414)),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 11, 12, 12, 21, 36, 60423)),
        ),
    ]
