# Generated by Django 4.2.3 on 2023-08-07 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 7, 23, 11, 57, 488219)),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 7, 23, 11, 57, 488219)),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 7, 23, 11, 57, 488219)),
        ),
        migrations.AlterField(
            model_name='requestedcomponents',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
