# Generated by Django 4.2.3 on 2023-08-23 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_app', '0002_alter_expenses_date_alter_income_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='deparment',
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 23, 16, 33, 3, 244138)),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 23, 16, 33, 3, 244138)),
        ),
        migrations.AlterField(
            model_name='member',
            name='department',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 23, 16, 33, 3, 244138)),
        ),
    ]
