# Generated by Django 4.2.4 on 2023-09-28 13:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio_app', '0002_alter_expenses_date_alter_income_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='deparment',
        ),
        migrations.AddField(
            model_name='requestcomponents',
            name='responseDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 9, 28, 13, 8, 59, 400183)),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 9, 28, 13, 8, 59, 399125)),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 9, 28, 13, 8, 59, 399579)),
        ),
        migrations.CreateModel(
            name='RespondedComponents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(max_length=255, null=True)),
                ('responseDate', models.DateTimeField(blank=True, null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='studio_app.component')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio_app.request')),
            ],
            options={
                'verbose_name_plural': 'responded Components',
            },
        ),
    ]
