# Generated by Django 4.2.3 on 2023-07-27 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_app', '0002_alter_member_options_alter_income_date_checkinandout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 27, 13, 39, 22, 812290)),
        ),
    ]
