# Generated by Django 4.2.3 on 2023-10-08 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_app', '0004_paymentsetting_alter_expenses_date_alter_income_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentsetting',
            options={'verbose_name_plural': 'Payment Setting'},
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 10, 8, 17, 29, 30, 363407)),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 10, 8, 17, 29, 30, 363407)),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 10, 8, 17, 29, 30, 363407)),
        ),
    ]
