# Generated by Django 4.2.3 on 2023-08-12 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_app', '0005_alter_expenses_date_alter_income_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 12, 18, 22, 36, 864021)),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 12, 18, 22, 36, 848396)),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 12, 18, 22, 36, 848396)),
        ),
    ]
