# Generated by Django 4.2.3 on 2023-09-25 07:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_app', '0005_alter_expenses_date_alter_income_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='respondedcomponents',
            options={'verbose_name_plural': 'responded Components'},
        ),
        migrations.AddField(
            model_name='requestcomponents',
            name='responseDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='respondedcomponents',
            name='responseDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 9, 25, 10, 9, 24, 578096)),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 9, 25, 10, 9, 24, 576102)),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 9, 25, 10, 9, 24, 577099)),
        ),
    ]
