# Generated by Django 4.2.3 on 2023-11-05 13:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio_app', '0005_alter_expenses_date_alter_income_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='value',
            new_name='unit',
        ),
        migrations.RemoveField(
            model_name='component',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='component',
            name='quantity',
        ),
        migrations.AddField(
            model_name='component',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 11, 5, 13, 30, 16, 255299)),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 11, 5, 13, 30, 16, 254317)),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 11, 5, 13, 30, 16, 254697)),
        ),
        migrations.CreateModel(
            name='LabComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='studio_app.component')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='studio_app.lab')),
            ],
            options={
                'verbose_name_plural': 'Lab Components',
            },
        ),
    ]
