# Generated by Django 4.2.3 on 2023-10-08 15:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio_app', '0005_alter_paymentsetting_options_alter_expenses_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 10, 8, 18, 0, 51, 58576)),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 10, 8, 18, 0, 51, 58576)),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 10, 8, 18, 0, 51, 58576)),
        ),
        migrations.CreateModel(
            name='MemberPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('paymentDate', models.DateField(default=datetime.datetime.now)),
                ('expieryDate', models.DateField()),
                ('remainingDays', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studio_app.member')),
            ],
        ),
    ]
