# Generated by Django 4.2.3 on 2023-10-08 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_app', '0006_alter_expenses_date_alter_income_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberpayment',
            name='status',
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 10, 8, 18, 38, 59, 606598)),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 10, 8, 18, 38, 59, 590927)),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 10, 8, 18, 38, 59, 590927)),
        ),
    ]
