# Generated by Django 4.2.3 on 2023-08-17 04:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_app', '0007_remove_request_email_alter_component_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='requested',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 17, 7, 27, 18, 434315)),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 17, 7, 27, 18, 434315)),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 17, 7, 27, 18, 434315)),
        ),
    ]
