# Generated by Django 4.2.3 on 2023-10-20 19:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_app', '0007_remove_memberpayment_status_alter_expenses_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberpayment',
            options={'verbose_name_plural': 'Member Payment'},
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 10, 20, 22, 41, 17, 668047)),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 10, 20, 22, 41, 17, 665059)),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 10, 20, 22, 41, 17, 666052)),
        ),
    ]
