# Generated by Django 4.2.3 on 2023-08-17 08:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_app', '0008_request_requested_alter_expenses_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestcomponents',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 17, 11, 37, 15, 234712)),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 17, 11, 37, 15, 234712)),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 17, 11, 37, 15, 234712)),
        ),
    ]
