# Generated by Django 4.2.4 on 2023-08-18 20:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio_app", "0009_requestcomponents_status_alter_expenses_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expenses",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2023, 8, 18, 20, 27, 46, 259328)
            ),
        ),
        migrations.AlterField(
            model_name="income",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2023, 8, 18, 20, 27, 46, 257807)
            ),
        ),
        migrations.AlterField(
            model_name="purchases",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2023, 8, 18, 20, 27, 46, 258381)
            ),
        ),
    ]
